system_prompt = """
You are a code expert. Given an incomplete function and the function body generated by another agent, your task is to evaluate and improve the function body, ensuring it meets the criteria.
"""

from compiler.langchain_bridge.interface import LangChainSemantic, LangChainLM, LMConfig
from compiler.optimizer.params.reasoning import ZeroShotCoT

code_finalize_semantic = LangChainSemantic(
  system_prompt=system_prompt,
  inputs=['incomplete_function', 'completed_code'],
  output_format="finalized_code",
  output_format_instructions="Please response with the function body only. Place the code within <result> and </result> tags. Do not include any additional text, explanations, or comments outside these tags"
)
lm_config = LMConfig(
  provider="openai",
  model="gpt-4o-mini",
  kwargs={"temperature": 0.0},
)
code_finalize_lm = LangChainLM(
  'code finalize', 
  code_finalize_semantic, 
  opt_register=True,
  lm_config=lm_config,
)

# ZeroShotCoT.direct_apply(code_finalize_lm)
code_finalize_agent = code_finalize_lm.as_runnable()